# Generated by Django 5.1.1 on 2024-09-29 12:17

from django.db import migrations

# def remove_dummy_data(apps, schema_editor):
#     # Get the models
#     User = apps.get_model('auth', 'User')
#     Vendor = apps.get_model('E_Waste_App', 'Vendor')
#     Product = apps.get_model('E_Waste_App', 'Product')

#     # Remove the dummy vendor and products
#     Product.objects.filter(vendor__user__username='John Doe').delete()
#     Vendor.objects.filter(user__username='John Doe').delete()
#     User.objects.filter(username='John Doe').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('E_Waste_App', '0002_auto_20240929_0220'),
    ]

    operations = [

    ]

